//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ProductItems = new HashSet<ProductItem>();
        }
    
        public int ItemID { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public string Url { get; set; }
        public string ImageUrl { get; set; }
        public string HTML { get; set; }
        public int WaitDays { get; set; }
        public string HTMLShort { get; set; }
        public bool IsFree { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public Nullable<int> PartID { get; set; }
    
        public virtual ItemType ItemType { get; set; }
        public virtual Part Part { get; set; }
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductItem> ProductItems { get; set; }
    }
}
