//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItem
    {
        public int ProductItemID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public int OldProductID { get; set; }
        public int OldItemID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Product Product { get; set; }
    }
}
