//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductItems = new HashSet<ProductItem>();
            this.SubscriptionProducts = new HashSet<SubscriptionProduct>();
        }
    
        public int ProductID { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> ProductLinkTextID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
    
        public virtual ProductLinkText ProductLinkText { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductItem> ProductItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionProduct> SubscriptionProducts { get; set; }
    }
}
